import { OrderStatus } from 'src/order/entities/order.entity';
import { ItemType } from 'src/order/entities/order-item.entity';
import {
  InvoiceStatus,
  InvoiceType,
  PaymentMethod,
} from 'src/invoice/entities/invoice.entity';
import { AppointmentStatus } from 'src/appointment/entities/appointment.entity';
import { AuditAction } from 'src/audit/enums/audit-action.enum';
import { AuditEntity } from 'src/audit/enums/audit-entity.enum';

export const createUserStub = (overrides: Record<string, any> = {}) => ({
  id: 'user-uuid',
  shortId: 'short-id1',
  firstName: 'Test',
  lastName: 'User',
  email: 'test@example.com',
  password: '$argon2id$v=19$m=65536,t=3,p=4$hashed',
  googleId: null,
  businessId: 'business-uuid',
  business: null,
  isEmailVerified: true,
  isSystem: true,
  isActive: true,
  hashedRefreshToken: null,
  avatarUrl: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  deletedAt: null,
  isGoogleUser: () => false,
  isLocalUser: () => true,
  ...overrides,
});

export const createBusinessStub = (overrides: Record<string, any> = {}) => ({
  id: 'business-uuid',
  shortId: 'biz-short',
  name: 'Test Business',
  email: 'biz@example.com',
  phone: '+1234567890',
  address: '123 Main St',
  city: 'Accra',
  state: 'Greater Accra',
  country: 'Ghana',
  ownerId: 'user-uuid',
  logo: null,
  categories: ['retail'],
  tagLine: 'Test tagline',
  description: 'A test business',
  taxId: null,
  registrationNumber: null,
  businessHours: null,
  isActive: true,
  website: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  deletedAt: null,
  ...overrides,
});

export const createCustomerStub = (overrides: Record<string, any> = {}) => ({
  id: 'customer-uuid',
  shortId: 'cust-short',
  businessId: 'business-uuid',
  name: 'John Doe',
  email: 'john@example.com',
  phone: '+1234567890',
  notes: 'A test customer',
  hashedPassword: null,
  appointments: [],
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  deletedAt: null,
  ...overrides,
});

export const createOrderItemStub = (overrides: Record<string, any> = {}) => ({
  id: 'order-item-uuid',
  orderId: 'order-uuid',
  itemType: ItemType.PRODUCT,
  name: 'Test Product',
  price: 50,
  quantity: 2,
  subTotal: 100,
  productId: 'product-uuid',
  serviceId: null,
  product: null,
  service: null,
  ...overrides,
});

export const createOrderStub = (overrides: Record<string, any> = {}) => ({
  id: 'order-uuid',
  orderNumber: 'ORD-ABCD1234',
  businessId: 'business-uuid',
  customerId: 'customer-uuid',
  customerName: 'John Doe',
  customerEmail: 'john@example.com',
  customerPhone: '+1234567890',
  invoiceId: null,
  status: OrderStatus.PENDING,
  totalAmount: 100,
  items: [createOrderItemStub()],
  business: null,
  invoice: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  ...overrides,
});

export const createInvoiceStub = (overrides: Record<string, any> = {}) => ({
  id: 'invoice-uuid',
  invoiceNumber: 'VEN-240101120000000-ABC123',
  businessId: 'business-uuid',
  customerId: 'customer-uuid',
  customerName: 'John Doe',
  customerEmail: 'john@example.com',
  customerPhone: '+1234567890',
  invoiceType: InvoiceType.STANDARD,
  business: null,
  orders: [],
  subtotal: 100,
  vatRate: 0.15,
  vatAmount: 15,
  nhilRate: 0.025,
  nhilAmount: 2.5,
  getfundRate: 0.025,
  getfundAmount: 2.5,
  totalTax: 20,
  totalAmount: 120,
  amountPaid: 0,
  status: InvoiceStatus.DRAFT,
  paymentMethod: null,
  paymentDate: null,
  issueDate: new Date('2024-01-01'),
  dueDate: new Date('2024-02-01'),
  notes: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  ...overrides,
});

export const createProductStub = (overrides: Record<string, any> = {}) => ({
  id: 'product-uuid',
  shortId: 'prod-short',
  businessId: 'business-uuid',
  name: 'Test Product',
  primaryImage: 'https://example.com/image.jpg',
  supportingImages: [],
  availableQuantity: 10,
  price: 50,
  description: 'A test product',
  notes: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  deletedAt: null,
  ...overrides,
});

export const createServiceStub = (overrides: Record<string, any> = {}) => ({
  id: 'service-uuid',
  shortId: 'svc-short',
  businessId: 'business-uuid',
  name: 'Test Service',
  primaryImage: null,
  supportingImages: [],
  price: 30,
  description: 'A test service',
  notes: null,
  businessHours: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  deletedAt: null,
  ...overrides,
});

export const createAppointmentStub = (overrides: Record<string, any> = {}) => ({
  id: 'appointment-uuid',
  shortId: 'appt-short',
  businessId: 'business-uuid',
  userId: 'user-uuid',
  customerId: 'customer-uuid',
  customer: null,
  title: 'Test Appointment',
  description: 'A test appointment',
  notes: null,
  startTime: new Date('2024-06-01T09:00:00Z'),
  endTime: new Date('2024-06-01T10:00:00Z'),
  status: AppointmentStatus.SCHEDULED,
  isRecurring: false,
  recurringFrequency: null,
  recurringUntil: null,
  googleEventId: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  deletedAt: null,
  ...overrides,
});

export const createAuditStub = (overrides: Record<string, any> = {}) => ({
  id: 'audit-uuid',
  action: AuditAction.CREATE,
  entity: AuditEntity.ORDER,
  entityId: 'order-uuid',
  userId: 'user-uuid',
  metadata: {},
  createdAt: new Date('2024-01-01'),
  ...overrides,
});
