export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const BUSINESS_REPOSITORY = 'BUSINESS_REPOSITORY';
export const MAILER_REPOSITORY = 'MAILER_REPOSITORY';
export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
