name: Reusable Deploy

on:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Determine tag based on branch (e.g., 'latest' for main, 'dev' for dev)
      - name: Set Image Tag
        id: image_tag
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            TAG="latest"
          else
            TAG="${{ github.ref_name }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: Docker/Dockerfile
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ steps.image_tag.outputs.tag }}
            ${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REPOSITORY_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REPOSITORY_NAME }}:buildcache,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}

      - name: Trigger Render Deploy
        run: |
          curl --silent --show-error --fail \
            --request POST \
            --url https://api.render.com/v1/services/srv-d52vjjemcj7s73dr4sr0/deploys \
            --header 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            --header 'Content-Type: application/json'
