name: Reusable Checks
on:
  workflow_call:

jobs:
  validate_branch:
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.check_branch.outputs.is_valid }}
    steps:
      - name: Check Branch Validity
        id: check_branch
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          if [[ $BRANCH_NAME =~ ^(feature\/|fix\/|hotfix\/|main$|develop$|dev$) ]]; then
              echo "Branch name is valid."
              echo "is_valid=true" >> $GITHUB_OUTPUT
          else
              echo "Branch name is invalid. Must start with feature/, fix/, or hotfix/"
              echo "is_valid=false" >> $GITHUB_OUTPUT
              exit 1
          fi
  validate_commit_messages:
    runs-on: ubuntu-latest
    needs: validate_branch
    if: needs.validate_branch.outputs.is_valid == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all commits for PRs to check messages
          fetch-depth: 0

      - name: Check Commit Message Convention (Conventional Commits)
        uses: wagoid/commitlint-github-action@v5
        # Configure commitlint to enforce rules (requires a commitlint config file, e.g., .commitlintrc.js)
        with:
          configFile: .commitlintrc.js
  lint:
    runs-on: ubuntu-latest
    needs: [ validate_branch, validate_commit_messages ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Linting
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm run test:e2e
